apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: resource-view
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/myonlyzzy/kubectl-resource-view/releases/download/v0.1.0/kubectl-resource-view_linux_amd64.tar.gz
    sha256: ""
    files:
      - from: "./resource-view"
      to: "."
    - from: LICENSE
      to: "."
    bin: "resource-view"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/myonlyzzy/kubectl-resource-view/releases/download/v0.1.0/kubectl-resource-view_darwin_amd64.tar.gz
    sha256: ""
    files:
      - from: "./resource-view"
      to: "."
    - from: LICENSE
      to: "."
    bin: "resource-view"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/myonlyzzy/kubectl-resource-view/releases/download/v0.1.0/kubectl-resource-view_windows_amd64.zip
    sha256: ""
    files:
      - from: "/resource-view.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "resource-view.exe"
  shortDescription: A new plugin
  homepage: https://github.com/myonlyzzy/kubectl-resource-view
  caveats: |
    Usage:
      $ kubectl resource-view

    For additional options:
      $ kubectl resource-view --help
      or https://github.com/myonlyzzy/kubectl-resource-view/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a plugin for view node resourde request  and  limit
